name: Clojure CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Tools setup
      uses: jdx/mise-action@v2
      with:
        install: true
        cache: true
    - name: Tools config
      run: |
        echo "JAVA_HOME=$(mise where java)" >> $GITHUB_ENV
        echo "GRAALVM_HOME=$(mise where java)" >> $GITHUB_ENV
        echo "$(mise where java)/bin" >> $GITHUB_PATH
        gu install native-image
    - name: Run tests
      run: make test
    - name: Run clj-kondo linter
      run: make lint
    - name: Run build jar
      run: make build
    - name: Run build app
      run: make build-native
